on: [push, pull_request]
name: Build
jobs:
  build:
    name: Build UxAS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        component: [uxas-ada, uxas, amase]
        qualifier: [scenario=release, scenario=gcov]
        python-version: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap anod
        run: |
          curl -L https://github.com/AdaCore/OpenUxAS-bootstrap/raw/master/install/bootstrap | bash

      - name: Patch bootstrap
        run: |
          envsubst < $GITHUB_WORKSPACE/.github/bootstrap.patch &> $HOME/subst-bootstrap.patch
          cat $HOME/subst-bootstrap.patch
          patch -d$HOME/bootstrap -p0 < $HOME/subst-bootstrap.patch
          cat $HOME/bootstrap/specs/config/repositories.yaml

      - name: Install GNAT CE 2020
        if: ${{ matrix.component == 'uxas-ada' }}
        uses: ada-actions/toolchain@v0.2.0
        with:
          distrib: community

      - name: Build with anod
        run: |
          SHELL=/bin/bash $HOME/bootstrap/vpython/bin/python $HOME/bootstrap/anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}

      - name: Run C++ tests
        if: ${{ matrix.component == 'uxas' }}
        run: |
          eval "$( $HOME/bootstrap/vpython/bin/python $HOME/bootstrap/anod -v printenv ${{ matrix.component }} --qualifier=${{ matrix.qualifier }} )"
          echo $PATH
          $HOME/bootstrap/vpython/bin/python $GITHUB_WORKSPACE/tests/cpp/run-tests

      - name: Run Ada tests
        if: ${{ matrix.component == 'uxas-ada' }}
        run: |
          eval "$( $HOME/bootstrap/vpython/bin/python $HOME/bootstrap/anod -v printenv ${{ matrix.component }} --build-env )"
          $HOME/bootstrap/vpython/bin/python $GITHUB_WORKSPACE/tests/proof/run-proofs -E --timeout=2400
